---
- hosts: localhost
  vars:
    helm_chart_url: "https://nomer26.github.io/Charts/argocd_charts/stable"
  tasks:
    - name: Remove helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_state: absent
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "{{ helm_chart_url }}"
    - name: Install ArgoCD Chart
      kubernetes.core.helm:
        name: argocd
        release_namespace: argo
        create_namespace: true
        chart_ref: argo/argo-cd
        values_files:
          - argo_values.yaml
    - name: Gather info about argocd
      kubernetes.core.helm_info:
        name: argocd
        namespace: argo
