---
- hosts: localhost
  name: Argo CD Helm
  vars:
    helm_chart_url: "https://argoproj.github.io/argo-helm"
  tasks:
    - name: Remove helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_state: absent
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "{{ helm_chart_url }}"
    - name: Install ArgoCD Chart
      kubernetes.core.helm:
        name: argo-cd
        release_namespace: argo
        create_namespace: true
        chart_ref: argo/argo-cd
        values_files:
          - argo_values.yaml
  
- hosts: localhost
  name: Prometheus Helm
  vars:
    helm_chart_url: "https://prometheus-community.github.io/helm-charts"
  tasks:
    - name: Remove helm repo
      kubernetes.core.helm_repository:
        name: prometheus
        repo_state: absent
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: prometheus
        repo_url: "{{ helm_chart_url }}"
    - name: Install Prometheus Chart
      kubernetes.core.helm:
        name: prom
        release_namespace: monitoring
        create_namespace: true
        chart_ref: prometheus/prometheus
        values_files:
          - prometheus_values.yaml

- hosts: localhost
  name: Grafana Helm
  vars:
    helm_chart_url: "https://grafana.github.io/helm-charts"
  tasks:
    - name: Remove helm repo
      kubernetes.core.helm_repository:
        name: grafana
        repo_state: absent
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: "{{ helm_chart_url }}"
    - name: Install Grafana Chart
      kubernetes.core.helm:
        name: grafan
        release_namespace: monitoring
        chart_ref: grafana/grafana
        values_files:
          - grafana_values.yaml
