apiVersion: v1
entries:
  cluster-autoscaler:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-07-11T03:07:37.929428935Z"
    description: A Helm chart for Kubernetes
    digest: 3b2c01f137ab5d92ef81ba281c36f5c5468313f9b0c86e30f8b3f5cbe40b04e1
    name: cluster-autoscaler
    type: application
    urls:
    - cluster-autoscaler-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-11T03:07:37.566036902Z"
